### ISSUE TITLE
Seems not to work on mobile

### ISSUE THREAD

**Issue by gop-aroy** [google/marzipano#62]
Hello,

First of all, thank you for your work, this is really helpful for the project i'm working on.

Unfortunately, I have some issues on mobile devices : i can't click on the hotspots.
You can see an example of my issue on this website (not mine, but same issue) : http://alvaromurcia.es/Area51/bonsais/

I'm using v0.5.3, the same as your demo that seems to work. Any idea ?

Thank you in advance for your help.

**Comment by Jermorin** [comment]
+1

**Comment by manuelcabral** [comment]
This seems to be due to an issue in the Marzipano tool that was fixed recently. You can probably fix it by replacing the tour's index.js by the latest version: http://www.marzipano.net/tool/template/app-files/index.js?3ba70d1

**Comment by Jermorin** [comment]
You close the issues before having a positive feedback from users :(

You recommended to update this file, however we do not use the demo file.

We did not open an issue to say that helloWorld does not work.
Everything works normally on desktop, clicking on the hotspot, loads the next scene well, however we notice a difference on mobile. Is there a different default behavior provided by the lib ?

**Comment by manuelcabral** [comment]
I assumed that the issue was the same than on the provided link. Since apparently it is not, do you have a link of your own so I can investigate the issue?

Marzipano does not handle clicking or tapping on hotspots, it only positions the hotspots on the panoramas. The user needs to add the desired event handlers. In the sample-tour demo that is done [here](https://github.com/google/marzipano/blob/3aaabcb4b0460cde635eae6240ac3c4696aaf380/demos/sample-tour/index.js#L262), for example.

That being said, the view control methods may interfere with these events unless stopPropagation() is called on them, since they [call preventDefault()](https://github.com/google/marzipano/blob/006327747449daf034f5bd2cc172747e219af4eb/src/controls/Drag.js#L109) on some events.

**Comment by jeanrespen** [comment]
Hi,

I have the same problem here. Getting a news index.js or the last marzipano.js does not fix the problem. It works perfectly on Desktop, but not on Android platform (neither Chrome nor Firefox). The hotspot is displayed, but it is impossible to click on it.

Do you have a fix ?

Best,

Jean
